### ISSUE TITLE
BUILD FAILED 

### ISSUE THREAD

**Issue by tiyee** [google/xi-mac#208]
```
libc++abi.dylib: terminating with uncaught exception of type NSException
Command /Applications/Xcode.app/Contents/Developer/usr/bin/actool failed with exit code 6

** BUILD FAILED **


The following build commands failed:
	CompileStoryboard XiEditor/Main.storyboard
	CompileAssetCatalog build/Release/XiEditor.app/Contents/Resources XiEditor/Assets.xcassets
(2 failures)
```
my xcode version is `Version 9.4.1 (9F2000)`
my rust version is `1.27.0`

**Comment by wolfadex** [comment]
@tiyee how did you end up resolving this issue? I'm also encountering it

**Comment by akashvacher** [comment]
I ran into the same issue, and I also had the same version of Xcode (Version 9.4.1), so leaving this comment here in case someone also gets to this page after web search.

The fix is mentioned by OP, but I'll expand on it: 
open xcode in App Store and just get the latest version (for me, it was Xcode 10.0). I did try to do this via CLI by running `softwareupdate --install --all` which _seemed_ to install xcode 10.0, but didn't actually do it for some reason. I tried the app store UI next and it worked like a charm (though it did take a lot of time to install)
