### ISSUE TITLE
UI line number

### ISSUE THREAD

**Issue by NateLing** [google/xi-mac#21]
![image](https://cloud.githubusercontent.com/assets/9606668/25259282/d3249384-2677-11e7-9763-04204638dc36.png)

like this picture, the line number error

**Comment by cbrewster** [comment]
This happens when using a non-monospaced font.

**Comment by cmyr** [comment]
yea we don't know how to measure 'character width' in a non-monospaced font. That's a holdover from older code, though, we could definitely be doing better here, by actually measuring the string in `updateGutterWidth()`

**Comment by NateLing** [comment]
@cbrewster  @cmyr   i am a web developer. in CSS compute fonts width throw font-size*characters. i dont know any help for you.

**Comment by rkusa** [comment]
I am wondering if the naive solution of `gutterColumns * max(stringWidth("0"), stringWidth("1"), stringWidth("2"), ..., stringWidth("9"))` (i.e. find out which of the numbers from 0-9 is the widest und use that as a replacement for the current `textMetrics.fontWidth`) is good enough?

This does not take kerning and ligatures into account, but since they usually tighten the spacing instead of widening it (this assumption could be wrong), they might not be an issue.

Otherwise, we could calculate the actual stringWidth of the numbers and maintain a cache for the widest number per column count.

**Comment by cmyr** [comment]
I don't particularly dislike this approach? Seems like a reasonable hack. Another option to consider is just baking in Inconsolata, and not letting the gutter font be changed... 🤔

**Comment by raphlinus** [comment]
A simpler approach would just be to measure 9's. It seems unlikely this
would be seriously wrong.

**Comment by cmyr** [comment]
Another option: when we're drawing each line number, we calculate expected drawing bounds. We could check this against the current gutter width, and if the width is inadequate we could fire a notification or otherwise indicate that the gutterview needs to be resized.

We could also just stash the max of this in the gutterview, and invalidate if the line count decreases?

**Comment by cbrewster** [comment]
Take the following example:
There is a file with 100+ lines, but we are only viewing the top 30 lines. The gutter will be the max width for 2 characters, but then as you scroll with lines 100+, the gutter would then resize to 3 characters wide. It would seem odd for the gutter to change width while scrolling.

**Comment by cmyr** [comment]
@cbrewster yea I was thinking about the corollary of this problem during the initial implementation: in a file with 10m lines, it looks weird to have a really wide gutter with a single number.

I agree with you in the general case, and I think for the time being just using `gutterColumns * stringWidth("9")` seems reasonable?

**Comment by jansol** [comment]
Shouldn't the gutter, being fixed UI, be using the System font anyway? (San Francisco or whatever the System font happens to be) There are functions for getting that and NSFont IIRC has a method for measuring strings.

**Comment by cmyr** [comment]
@jansol this is definitely a design decision. Xcode, for instance, has a predefined gutter font (which may not be the system default?), but sublime text uses the user font.

**Comment by jansol** [comment]
Either way, [this](https://developer.apple.com/documentation/foundation/nsstring/1524729-boundingrect) looks like the way to go. At least as long as our screens aren't going to fit 10k lines.
