### ISSUE TITLE
Cmd-Z should move the cursor to the point where the undo happens

### ISSUE THREAD

**Issue by afgomez** [google/xi-mac#233]
Hi!

First of all, thanks for the job you're doing in the editor :) I gave it a try and found a small usability issue. When editing a long file (more than one scroll page), moving the cursor, and undoing, the cursor should move back to the point where the previous edit happened.

### Steps to reproduce:
1. Open a long file
2. Write something on the top of the file
3. Scroll down, and click somewhere so the cursor moves.
4. Press `Cmd-Z`

### What happens:
Text written in step 2 gets undoed, but there's no visual feedback. The cursor stays where it is.

### What should happen:
The cursor and the scroll move to where the undo is happening.

### Commits where it happens:
xi-mac: f5ee18b6ae0304efd45e8c33f0782550a86398e6
xi-editor: a417a3afb0b13dba09b44c9b93ec92cc6cb09ddd

Cheers.

**Comment by cmyr** [comment]
@afgomez thanks for the issue, I agree that some feedback when an undo occurs out of view would be useful. Implementing this will be work in xi-core; if you'd like to open an issue [there](https://github.com/google/xi-editor/) that might be best, otherwise I'll leave this here and move it over next time we do issue cleanup. 😄

**Comment by afgomez** [comment]
@cmyr do you mean xi-editor? I'll close this issue and open another one there then.

**Comment by cmyr** [comment]
@afgomez thanks!
